### ISSUE TITLE
Error making GET request: Unauthorized

### ISSUE THREAD

**Issue by mauricionr** [OfficeDev/PnP-JS-Core#174] opened 2016-08-15 20:02 UTC
#### Category
[ ] Enhancement

[ x] Bug

[ ] Question

I'm trying to get all lists in my site collection, a few days ago it was working fine

this is my permissions

```xml
  <AppPermissionRequests AllowAppOnlyPolicy="true">
    <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
    <AppPermissionRequest Scope="http://sharepoint/social/tenant" Right="FullControl" />
    <AppPermissionRequest Scope="http://sharepoint/search" Right="QueryAsUserIgnoreAppPrincipal" />
  </AppPermissionRequests>
```

#### Observed Behavior

x-ms-diagnostics:"3000006;reason="Token contains invalid signature.";category="invalid_client""

Thanks!

**Comment by mike-morrison** [comment] 2016-08-15 22:09
@mauricionr Can you get the url the library is trying to access and hit it directly in the browser.  

Is there a different error?

**Comment by mike-morrison** [comment] 2016-08-15 22:46
Can you please try creating a new app id, give it the same permissions and see if you still get the error?  This can help determine if it is an issue with the registration or the environment.

**Comment by mauricionr** [comment] 2016-08-16 12:17
@mike-morrison i will try again

Thanks

**Comment by mauricionr** [comment] 2016-08-16 14:27
@mike-morrison i've created another app, grant permissions and i'm still getting 401

```javascript
pnp.setup({
    nodeClientOptions: {
     clientId: '247c301c-a69b-462d-8964-74aa13289647',
     clientSecret: '{secret}',
     siteUrl: 'https://{company}.sharepoint.com/sites/{devSite}/'
   },
    headers: {
        "Accept": "application/json; odata=verbose"
    }
});

pnp.sp.web.select("Title").get()
    .then((web) => {
        console.log(web.Title);
    })
    .catch(error => {
        console.log(error);
    });;

pnp.sp.web.lists.get()
    .then((response) => {
        console.log(response.length)
    })
    .catch(error => {
        console.log(error);
    });

```


```logs
[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node .\index.js`
Error making GET request: Unauthorized
Error making GET request: Unauthorized
rs
[nodemon] starting `node .\index.js`
Error making GET request: Unauthorized
Error making GET request: Unauthorized
rs
[nodemon] starting `node .\index.js`
Error making GET request: Unauthorized
Error making GET request: Unauthorized

```

**Comment by mauricionr** [comment] 2016-08-22 20:32
@patrick-rodgers @mike-morrison  I've created a Dev Tenant from Office 365 dev program and got the same error

**Comment by sksnips** [comment] 2016-08-23 04:58
I am also getting the same error, when accessing SharePoint from Node console application. Any luck?

**Comment by patrick-rodgers** [comment] 2016-08-23 14:44
Hi all, I am able to reproduce this. I am not aware of any changes in our code that would affect this behavior - so I've reached out to see if there is anything happening in the service. I am leaving for vacation today in fact so won't have a chance to follow up until next week. Can be discussed in the weekly call on Thursday as well with @VesaJuvonen who might have some more info then.

**Comment by patrick-rodgers** [comment] 2016-08-23 15:54
There has been an update to the service and it looks like it is just hitting all of the tenants. I was able to get things working again by following these steps:

1.  Register the add-in in the site you want to read's appregnew.aspx page. http://tenant.sharepoint.com/_layouts/appregnew.aspx
2. Go to the appinv page **in your admin site** and grant the permissions http://tenant-admin.sharepoint.com/_layouts/appinv.aspx
3. Go back to the site you want to read and register the below permissions in that site's appregnew.aspx:

```
  <AppPermissionRequests AllowAppOnlyPolicy="true" >
  </AppPermissionRequests>
```

There may be more efficient ways to do this, but these steps appear to work in my quick testing. As I said above, leaving for vacation so will leave this issue open for further investigation - but I do not think this is an issue with the library, but rather with how we are registering the perms. Once we sort out the new process the wiki can be updated (anyone is welcome to update, no need to wait for me to return).

**Comment by mauricionr** [comment] 2016-08-23 16:10
It's kind weird, i did almost the same thing you said now, instead of

1. Register the add-in in the site you want to read's appregnew.aspx page. http://tenant.sharepoint.com/_layouts/appregnew.aspx
2. Go to the appinv page in your admin site and grant the permissions http://tenant-admin.sharepoint.com/_layouts/appinv.aspx
 ```xml
 <AppPermissionRequests AllowAppOnlyPolicy="true">
    <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
    <AppPermissionRequest Scope="http://sharepoint/social/tenant" Right="FullControl" />
    <AppPermissionRequest Scope="http://sharepoint/search" Right="QueryAsUserIgnoreAppPrincipal" />
  </AppPermissionRequests>
```
   
3. Go back to the site you want to read and register the below permissions in that site's http://tenant.sharepoint.com/_layouts/appinv.aspx: **appinv.aspx**
  ```xml
  <AppPermissionRequests AllowAppOnlyPolicy="true" >
  </AppPermissionRequests>
  ```

Before adding the step 3 i got 401 after adding it's working but debugging the NodeFetchClient.getRealm show 401 as in the screenshot

![image](https://cloud.githubusercontent.com/assets/2263551/17899703/94579528-6932-11e6-987b-cb451e9fafad.png)


but in the callback i could get the right response

![image](https://cloud.githubusercontent.com/assets/2263551/17899792/dceef448-6932-11e6-82b4-f76bba9d2cce.png)

**Comment by patrick-rodgers** [comment] 2016-08-23 16:26
Getting the realm will always come back as 401 - that is expected. That is a trick to get the realm since the realm is returned in the 401 response. Glad you are unblocked. Perhaps there is a smoother way to do this, but for now at least you can proceed. Maybe you or others will have time while I am out to explore options - I'll check in once I am back.

**Comment by mauricionr** [comment] 2016-08-23 16:47
Thanks @patrick-rodgers.

**Comment by patrick-rodgers** [comment] 2016-09-02 12:58
I updated the wiki article on this, so closing issue. Thanks for reporting it!

**Closed by patrick-rodgers** 2016-09-02 12:58 UTC
Labels: documentation
