### ISSUE TITLE
TSLint errors question

### ISSUE THREAD

**Issue by pr0peller** [OfficeDev/PnP-JS-Core#98] opened 2016-05-09 15:39 UTC
Hi,
I'm trying to build the solution and I keep getting errors during linting process. 
`Declaration of private instance member variable not allowed to appear after declaration of public instance member function`.

few files only, but enough to ruin the build. Everything builds and test pass without linting.
Does anybody experience the same issue or it's just me?

Thanks in advance

**Comment by pbjorklund** [comment] 2016-05-09 17:46
Hi @pr0peller. If you paste the output here I can check it tomorrow

**Comment by pr0peller** [comment] 2016-05-09 17:55
Hi,
Here it is the output from my console: 

`>npm test

> sp-pnp-js@0.0.10 test D:\__Source\Repos\PnP-JS-Core
> gulp test

(node:14208) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[20:08:50] Using gulpfile D:\__Source\Repos\PnP-JS-Core\gulpfile.js
[20:08:50] Starting 'lint'...
[20:08:50] Starting 'build-typings'...
[20:08:50] Starting 'clean'...
[20:08:50] Starting 'build-tests'...
[20:08:51] [gulp-tslint] error (member-ordering) collections/collections.ts[30, 5]: Declaration of private instance member variable not allowed to appear after declaration of public instance member function
[20:08:51] [gulp-tslint] error (member-ordering) configuration/configuration.ts[41, 5]: Declaration of private instance member variable not allowed to appear after declaration of public instance member function
[20:08:51] Finished 'clean' after 603 ms
[20:08:51] [gulp-tslint] error (member-ordering) net/HttpClient.ts[13, 5]: Declaration of private instance member variable not allowed to appear after declaration of public instance member function
[20:08:51] [gulp-tslint] error (member-ordering) utils/storage.ts[197, 5]: Declaration of public instance member variable not allowed to appear after declaration of public instance member function
[20:08:52] [gulp-tslint] error (member-ordering) sharepoint/rest/Queryable.ts[51, 5]: Declaration of public instance member variable not allowed to appear after declaration of public instance member function
[20:08:52] [gulp-tslint] error (eofline) sharepoint/rest/contenttypes.ts[222, 2]: file should end with a newline
[20:08:55] [gulp-tslint] error (member-ordering) sharepoint/rest/search.ts[246, 5]: Declaration of private instance member variable not allowed to appear after declaration of public instance member function
[20:08:55] [gulp-tslint] error (member-ordering) sharepoint/rest/search.ts[309, 5]: Declaration of public instance member variable not allowed to appear after declaration of public instance member function
[20:08:55] [gulp-tslint] error (member-ordering) sharepoint/rest/userprofiles.ts[15, 5]: Declaration of private instance member variable not allowed to appear after declaration of public instance member function
[20:08:56] 'lint' errored after 5.81 s
[20:08:56] Error in plugin 'gulp-tslint'
Message:
    Failed to lint: collections/collections.ts[30, 5]: Declaration of private instance member variable not allowed to appear after declaration of public instance member function, configuration/configuration.ts[41, 5]: Declaration of private instance member variable not allowed to appear after declaration of public instance member function, net/HttpClient.ts[13, 5]: Declaration of private instance member variable not allowed to appear after declaration of public instance member function, utils/storage.ts[197, 5]: Declaration of public instance member variable not allowed to appear after declaration of public instance member function, sharepoint/rest/Queryable.ts[51, 5]: Declaration of public instance member variable not allowed to appear after declaration of public instance member function, sharepoint/rest/contenttypes.ts[222, 2]: file should end with a newline, sharepoint/rest/search.ts[246, 5]: Declaration of private instance member variable not allowed to appear after declaration of public instance member function, sharepoint/rest/search.ts[309, 5]: Declaration of public instance member variable not allowed to appear after declaration of public instance member function, sharepoint/rest/userprofiles.ts[15, 5]: Declaration of private instance member variable not allowed to appear after declaration of public instance member function.
[20:08:57] Finished 'build-tests' after 7.05 s
[20:08:57] Finished 'build-typings' after 7.15 s
npm ERR! Test failed.  See above for more details.

D:\__Source\Repos\PnP-JS-Core (dev) (sp-pnp-js@0.0.10)`

**Comment by mike-morrison** [comment] 2016-05-09 18:03
@pbjorklund @pr0peller I got these same errors out of nowhere the other day.  I had to move all of the failing items above the constructor to make the errors go away.  I assumed the tslint rules changed and that a PR was probably pending already to fix it.

**Comment by pr0peller** [comment] 2016-05-09 18:06
Same here. Lint was fine yesterday. Thanks for the info @mike-morrison

**Comment by pbjorklund** [comment] 2016-05-09 18:16
Is this against the master or dev branch?

**Comment by pr0peller** [comment] 2016-05-09 18:28
@pbjorklund  It is against dev branch

**Comment by pr0peller** [comment] 2016-05-09 18:30
@pbjorklund  Same issue against master branch - just checked!

**Comment by patrick-rodgers** [comment] 2016-05-09 23:30
I just pulled dev and ran gulp lint and could not reproduce this. tslint rules haven't changed so far as I am aware.

**Comment by biste5** [comment] 2016-05-09 23:33
I could reproduce it couple of days back from dev branch, while working on my PR.

I didn't commit my tslint.json then, which I used to check successful build. Wanted to raise the issue myself too

**Comment by russgove** [comment] 2016-05-10 00:12
I had the isues on Saturday and changed my talking to fix it

**Comment by mike-morrison** [comment] 2016-05-10 00:30
I noticed it for the first time on a Mac, but I am pretty sure I got it on Windows too.

**Comment by patrick-rodgers** [comment] 2016-05-10 03:54
I just noticed you are doing "npm test" instead of "gulp test". I re-pulled latest from dev and tried that and it worked as expected. So far as I know nothing had changed on my machine, and I am pulling from the dev branch in git with no local changes. tslint.json hasn't been updated in some time. Unsure, if someone who can reproduce this can investigate that would be appreciated but everything appears fine. I have version 3.3.12 of tslint, but haven't done anything special to it (at least that I am aware of).

**Comment by biste5** [comment] 2016-05-10 08:18
It has to do with an [issue in TSLint](https://github.com/palantir/tslint/issues/1205) seems, not with what we were doing.
So it's depending on which version of TSLint is being used and should be fixed soon.

I'm using TSLint 3.8.0 and have the issue.

**Comment by pbjorklund** [comment] 2016-05-10 10:20
It has to do with the fact that we use caret ranges for tslint and gulp-tslint. @biste5 is most likely correct that it will be solved upstream soon enough.

We could lock down versions to specific versions in package.json.

For now you can resolve with ```npm install tslint@3.6.0 gulp-tslint@4.3.2```

**Comment by pr0peller** [comment] 2016-05-10 10:38
I'll check my version of TSLint when I get home, but I think I'm running 3.8.0 also. Not 100% sure though ...

**Comment by pr0peller** [comment] 2016-05-10 15:54
I'm using TSLint 3.9.0 downgradet to 3.6.0 as @pbjorklund advice and now it is ok.

**Comment by patrick-rodgers** [comment] 2016-05-10 17:39
So before I close this want to confirm:
1. It is now working
- this was due to an issue with tslint and not a change in our library somewhere?

**Comment by pr0peller** [comment] 2016-05-10 17:41
Correct, With TSLint 3.6.0 works. The Issue is in the newer version of TSLint tool.

**Comment by patrick-rodgers** [comment] 2016-05-10 17:42
Thanks, I'll close this. Appreciate everyone who had a look.

**Closed by patrick-rodgers** 2016-05-10 17:42 UTC
Labels: investigate
