### ISSUE TITLE
use $expand and $select with caml query

### ISSUE THREAD

**Issue by russgove** [OfficeDev/PnP-JS-Core#96] opened 2016-05-07 21:28 UTC
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

####Category
[x ] Enhancement

[ ] Bug

[ ] Question
I was looking to see how I could convert an existing projext to use this library.
In one of my queries I have this:

> var url = this.getHostApiUrl("Web/Lists/GetByTitle('" + listTitle + "')/getitems?$expand=ContentType,Folder,Folder/ParentFolder,File,File/ParentFolder,RoleAssignments,RoleAssignments/RoleDefinitionBindings,RoleAssignments/Member,RoleAssignments/Member/Users,RoleAssignments/Member/Groups,RoleAssignments/Member/UserId");
            var caml = "<View Scope='RecursiveAll'>" +
                        " <Query>" +
                             "<Where>" +
                              "   <Eq>" +
                               "      <FieldRef Name='FileDirRef'/>" +
                                "     <Value Type='Lookup'>" +
                                folderServerRelativeUrl +
                                 "    </Value>" +
                                " </Eq>" +
                            " </Where>" +
                       "  </Query>" +
   
                    " </View>";
            var queryPayload = {
                'query': {
                    '__metadata': { 'type': 'SP.CamlQuery' },
                    'ViewXml': caml
                }
            };
            var folderLoaded = $q.defer();

I'm passing in a Caml query and also using $expand and $select.
The current inplementation of getItemsByCamlQuery, makes the call to sharepoint imeediately and returns the deferrerd. No chance to update it with $select or $expand (which I have working in my local repo).I We could make it so that We can use a Caml query and also be able to use $select and $expand.

I think  I would want to do code something like this:
$pnp.sp.web.lists.getByTitle('Style Library').caml(q).select('Title').expand('RoleAssignments').get()

**Comment by patrick-rodgers** [comment] 2016-05-13 18:03
The issue is you have to do a POST request for the caml query, it doesn't work with get per the docs. Can you not use the View XML to specify the fields to return? You should be able to fully describe the query using that xml. I am also not sure it is a good idea to mix the CAML and OData query methods.

**Comment by russgove** [comment] 2016-05-14 01:41
Hi Patrick,
We can use the XML to specify the fields to return, the filters, and the orderby. Just not the expands(as done in my example above). If anyone knows a way to do that in caml that would be great.

I've got it almost ready in my branch by adding the 'caml; method to lists.js:
  public caml(caml: string): QueryableCollection {
        debugger;
        let  items = new Items(this);
        items._caml = caml;
        return items;
   }
and then i'm overriding the get method there as well:
 public get(): Promise<any> {
         if (this._caml !== "")    {
             return super.post();// need to add logic to format post request
         }
         return super.get();
    }

**Comment by patrick-rodgers** [comment] 2016-05-20 13:17
Appears you are correct in that expand is not supported. I am going to update the getItemsByCAMLQuery to take an optional parameter of expanded fields. So you can call getItemsByCAMLQuery(xml, "User\Email", "User\Login", ...) and it will just append the expands. I'll create  PR and link it here.

**Comment by russgove** [comment] 2016-05-20 14:39
That's a good start. In my opinion I think it would be easier on consumers
of this library to have the full set of odata query parameters.

if someone needs to do a query for something not supported in the rest api
(for example filter items based on multivalued taxonomy fields) , or has a
complex query that he thinks is more easily represented in cam than a
$filter string, it would be nice to let him do so, and still use the other
query parameters. For example , what if he wanted to page through the
results? he needs toi go in and modify his caml to do that? Why not just
let him use $skp and $top.  Use caml for what its good at and use rest for
what its good at.

Just my opininion

**Comment by patrick-rodgers** [comment] 2016-05-20 14:58
[Here is the change](https://github.com/OfficeDev/PnP-JS-Core/blob/dev/src/sharepoint/rest/lists.ts#L300)

I would like to encourage folks to use the REST api as much as possible. Mixing the odata and caml queries is not a great idea since they can conflict leading to unexpected behaviors that are hard to debug. Also to take your example $skip doesn't work with list items - so that would be doubly confusing. Philosophically I don't have a problem making people update a caml query if the caml query has changed (ie to page). Adding expands makes sense as it isn't supported by CAML.

**Comment by patrick-rodgers** [comment] 2016-06-03 14:55
Going to close this, added support for expand for CAML queries. If there is great demand we can revisit this but want to encourage folks to use the REST apis as a first choice.

**Closed by patrick-rodgers** 2016-06-03 14:55 UTC
Labels: enhancement

**Comment by jca38** [comment] 2018-06-07 12:12
Hi Patrick,
I would be interested to know how to replace a getItemsByCamlQuery(...) by OData REST operators when you have to filter items depending on lookup column or other filter criteria.
Thanks for your help,
Best Regards,
Jean-Christophe AUDARD

**Comment by jca38** [comment] 2018-06-07 12:14
I cannot retrieve File information (File Name, extension) using getItemsByCAMLQuery(...) in my document library, that's why I'm interested to replace it by classic OData REST operators...
Jean-Christophe
