### ISSUE TITLE
The number of items in this list exceeds the list view threshold

### ISSUE THREAD

**Issue by mauricionr** [OfficeDev/PnP-JS-Core#203] opened 2016-09-20 23:25 UTC
#### Category
[x ] Enhancement

[ ] Bug

[ x] Question

#### Expected / Desired Behavior / Question
Return all items in a list from SharePoint Rest API

#### Observed Behavior
more than 5000 items getting error while reading the list
The number of items in this list exceeds the list view threshold

#### Steps to Reproduce
List with more than 5000
Get item requesting more than 5000
```javascript
$pnp.sp.web.lists.getByTitle('Batch').items.top(10000).get(callback)
```

Thanks!

**Comment by koltyakov** [comment] 2016-09-21 08:25
Hi Mauricio,

You can't provide $top more than a throttling limit. By default, the throttling limit equals to 5000 for a list view. Any view should return less than this value to work.
If you deal with some export long running procedures you can use something similar which is described in https://github.com/OfficeDev/PnP-JS-Core/issues/204, in apps it's better to build the "views" to be less than 5000. 
Then you filtering large list with filters or CAML results after the first condition over the indexed field should be less than throttling to work, alas, $top will not help when "incorrect" filtering is in place.

**Comment by mauricionr** [comment] 2016-09-23 18:47
After the list reach more than 5000 items, if i try to get any top(x<5000) i got this error, 

`The number of items in this list exceeds the list view threshold`

After create a indexed column in the list i could get the items top(100)

it is important to index any column after reach more than 5000 item?

**Comment by koltyakov** [comment] 2016-09-23 19:18
By wrong indexing it's possible to make it worse, never abuse with indexes.
It's better not indexing at all than apply indexes incorrectly.
Query/view filtering will work only if data array is less than 5000 after applying first logical condition with use if indexed field, also, not every operand can be used for this, e.g. `not equal` or `in` won't work.
I would highly recommend using search API instead in case of complex filtering conditions.

**Comment by patrick-rodgers** [comment] 2016-10-04 10:27
Going to close this as by design - there is nothing we can do in the library, nor should do, to circumvent the throttling. Paging can be used to aggregate items for those rare cases where large numbers are needed. It is not recommended to do operations on large numbers of items in the browser.

**Closed by patrick-rodgers** 2016-10-04 10:27 UTC
Labels: discussion
